[package]
name = "native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
colorgrad = "0.6.2"
flutter_rust_bridge = "1"
image = "0.24.7"
pcap-parser = "0.14.0"
pulldown-cmark = "0.9.3"
